# Generated by Django 4.0.5 on 2022-06-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_mangatitle_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangachapter',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='mangatitle',
            name='slug',
        ),
        migrations.AlterField(
            model_name='mangachapter',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mangatitle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
