# Generated by Django 4.0.5 on 2022-06-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_remove_mangachapter_slug_remove_mangatitle_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangachapter',
            name='URL',
            field=models.URLField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
