# Generated by Django 4.0.5 on 2022-06-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_mangachapter_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangachapter',
            name='last_read',
        ),
        migrations.AddField(
            model_name='mangatitle',
            name='last_read',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
