# Generated by Django 4.0.5 on 2022-06-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_remove_mangachapter_last_read_mangatitle_last_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangatitle',
            name='image_link',
            field=models.URLField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
