# Generated by Django 4.0.5 on 2022-06-24 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_mangachapterstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangachapterstatus',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.mangachapter'),
        ),
    ]
