# Generated by Django 4.0.5 on 2022-06-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_alter_mangachapterstatus_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangatitle',
            name='URL',
            field=models.URLField(max_length=255, verbose_name='Ссылка на тайтл'),
        ),
        migrations.AlterField(
            model_name='mangatitle',
            name='image_link',
            field=models.URLField(max_length=255, verbose_name='Ссылка на картинку'),
        ),
        migrations.AlterField(
            model_name='mangatitle',
            name='last_read',
            field=models.CharField(max_length=255, verbose_name='Последняя прочитанная глава'),
        ),
    ]
