# Generated by Django 4.0.5 on 2022-07-11 10:12

import Core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0011_category_alter_image_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='link',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=1, upload_to=Core.models.Image.save_override),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='mangachapter',
            name='URL',
            field=models.URLField(max_length=255, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='mangachapter',
            name='chapter_number',
            field=models.CharField(max_length=255, verbose_name='Номер главы'),
        ),
        migrations.AlterField(
            model_name='mangachapterstatus',
            name='status',
            field=models.CharField(choices=[('r', 'Read'), ('u', 'Unread'), ('n', 'No information')], default='n', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='mangachapterstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='mangatitle',
            name='categories',
            field=models.ManyToManyField(null=True, to='Core.category', verbose_name='Категории'),
        ),
    ]
