# Generated by Django 4.0.5 on 2022-07-11 10:15

import Core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_remove_image_link_image_image_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangatitle',
            name='image_link',
        ),
        migrations.AddField(
            model_name='mangatitle',
            name='image',
            field=models.ImageField(default=1, upload_to=Core.models.MangaTitle.save_override),
            preserve_default=False,
        ),
    ]
