# Generated by Django 4.0.5 on 2022-07-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_remove_mangatitle_image_link_mangatitle_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AlterField(
            model_name='mangatitle',
            name='categories',
            field=models.ManyToManyField(to='Core.category', verbose_name='Категории'),
        ),
    ]
