# Generated by Django 4.0.5 on 2022-07-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0015_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangatitle',
            name='parser_ulr',
            field=models.URLField(max_length=255, null=True, verbose_name='Ссылка для парсера'),
        ),
    ]
