# Generated by Django 4.0.5 on 2022-07-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0016_mangatitle_parser_ulr'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangatitle',
            name='dir',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
