# Generated by Django 4.0.5 on 2022-07-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0018_alter_mangachapter_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangachapter',
            name='chapter_number',
            field=models.FloatField(verbose_name='Номер главы'),
        ),
    ]
